-- MySQL Script generated by MySQL Workbench
-- Thu May 26 20:03:18 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema happyhousefinal
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema happyhousefinal
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `happyhousefinal` DEFAULT CHARACTER SET utf8 ;
USE `happyhousefinal` ;

-- -----------------------------------------------------
-- Table `happyhousefinal`.`member`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `happyhousefinal`.`member` (
  `id` VARCHAR(20) NOT NULL,
  `userclass` INT NULL DEFAULT NULL,
  `password` VARCHAR(20) NULL DEFAULT NULL,
  `username` VARCHAR(20) NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `happyhousefinal`.`notice`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `happyhousefinal`.`notice` (
  `noticeno` INT NOT NULL AUTO_INCREMENT,
  `writer` VARCHAR(45) NOT NULL,
  `title` VARCHAR(100) NOT NULL,
  `content` MEDIUMTEXT NOT NULL,
  `regdate` DATE NULL DEFAULT NULL,
  `userid` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`noticeno`, `userid`),
  INDEX `fk_notice_user1_idx` (`userid` ASC) VISIBLE,
  CONSTRAINT `fk_notice_user1`
    FOREIGN KEY (`userid`)
    REFERENCES `happyhousefinal`.`member` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `happyhousefinal`.`comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `happyhousefinal`.`comment` (
  `commentno` INT NOT NULL AUTO_INCREMENT,
  `writer` VARCHAR(45) NULL DEFAULT NULL,
  `userid` VARCHAR(45) NULL DEFAULT NULL,
  `content` MEDIUMTEXT NULL DEFAULT NULL,
  `regdate` DATE NULL DEFAULT NULL,
  `noticeno` INT NULL DEFAULT NULL,
  PRIMARY KEY (`commentno`),
  INDEX `fk_comment_notice1_idx` (`noticeno` ASC) VISIBLE,
  CONSTRAINT `fk_comment_notice1`
    FOREIGN KEY (`noticeno`)
    REFERENCES `happyhousefinal`.`notice` (`noticeno`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `happyhousefinal`.`interest`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `happyhousefinal`.`interest` (
  `interestno` INT NOT NULL AUTO_INCREMENT,
  `apartname` VARCHAR(200) NOT NULL,
  `address` VARCHAR(200) NULL DEFAULT NULL,
  `userid` VARCHAR(20) NOT NULL,
	`date` VARCHAR(20) NOT NULL,
  `price` VARCHAR(20) not null,
  `x` double NOT NULL,
  `y` double NOT NULL,
  PRIMARY KEY (`interestno`, `userid`),
  INDEX `fk_interest_user_idx` (`userid` ASC) VISIBLE,
  CONSTRAINT `fk_interest_user`
    FOREIGN KEY (`userid`)
    REFERENCES `happyhousefinal`.`member` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `happyhousefinal`.`news`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `happyhousefinal`.`news` (
  `newsno` INT NOT NULL AUTO_INCREMENT,
  `url` VARCHAR(200) NULL DEFAULT NULL,
  `title` VARCHAR(200) NULL DEFAULT NULL,
  `preview` VARCHAR(200) NULL DEFAULT NULL,
  `writing` VARCHAR(45) NULL DEFAULT NULL,
  `imgsrc` VARCHAR(200) NULL DEFAULT NULL,
  PRIMARY KEY (`newsno`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
